### ISSUE TITLE
Testing extracted NN module

### ISSUE THREAD

**Issue by jatkinson1000** [m2lines/convection-parameterization-in-CAM#13]
Now that we have the PyTorch and Fortran versions of the neural network, we should starting adding tests. Ideally, we should like

- Instructions for running the tests.
- Tests for the net's forward pass function in fortan.
- Tests for the ReLU function in fortran.
- Tests to make sure the model outputs are identical in both Fortran and PyTorch.

**Comment by dorchard** [comment]
These tests were already carried out by Yanni.
