### ISSUE TITLE
Clarify project aims and deliverables

### ISSUE THREAD

**Issue by jatkinson1000** [m2lines/convection-parameterization-in-CAM#16]
We need to clarify some of end deliverables of this particular piece of work.

This repository aims to:
- extract the Neural Net from [Yani & O'Gorman](https://github.com/yaniyuval/Neural_nework_parameterization/tree/main/NN_training) into a standalone fortran module
- deploy this extracted module into (specifically) the [Single Column Atmospheric Model](https://www.cesm.ucar.edu/models/simple/scam) of CESM

This repository does _not_ aim to:
- deploy ML models other than Yani & O'Gorman
- deploy models into CESM/CAM configurations other than SCAM

Once confirming these we need to:
- Update the repository title to reflect CAM vs SCAM
- Update the readme to reflect the project goals and aims

**Comment by jatkinson1000** [comment]
I think we are happy with this now, propose we close this issue to keep tidy at next review meeting.

**Comment by mondus** [comment]
This can be closed once @mondus and @dorchard have completed a project allocation request so that the end of this project is well understood and documented.
