### ISSUE TITLE
Planning the integration with CESM

### ISSUE THREAD

**Issue by mondus** [m2lines/convection-parameterization-in-CAM#18]
We should plan and understand the integration between the neural-network-based convection parameterisation, [CESM](https://github.com/ESCOMP/CESM), SCAM /CAM.

- How should these things depend on each other?
  - Should we consider sub-modules where appropriate?
- Separate repos which are not directly linked?

**Comment by dorchard** [comment]
We want to be able to call both the old deep convection scheme (Zhang-McFarlane) and the new scheme at the same time. This work could also replace shallow convection (as well as deep convection); therefore Therefore the place we are going to call our code form is the grid physics module.

**Comment by jatkinson1000** [comment]
Comments from Paul taken from #38 regarding testing variable conversion between CAM and SAM:

> Here is some brainstorming of additional tests that might be useful:
> - Make sure that the transformation (qv,qcc,qii,tabs)<->(q,t) returns the same values when we use it in the forward direction followed by the reverse direction
> - Implement the new parameterization with CAM type inputs (qv, qcc, qii, tabs) in SAM and see that it gives similar results to the original implementation.
> - For a few sample temperatures and values of q (some high q so there is cloud and some low q so there is no cloud), calculate the transformation (q,t)->(qv,qcc,qii, tabs) and compare the results with an independent calculation using equations in the appendix of the original SAM paper (https://doi.org/10.1175/1520-0469(2003)060<0607:CRMOTA>2.0.CO;2)

**Comment by dorchard** [comment]
Further useful details from @judithberner

> [re the ML-deep convective parameterization]: the input is a state and the output is a deep convective tendency.
In this case we will call your routines from physpkg.f90 and replace X_tend and X_tend2.
We would keep the  X_register, X_init, X_tend routines since they add the necessary fields to be buffer pbuf (X_register) and initialize them 
to zero at the beginning of the timstep ( X_init), so we would need to replace X_tend and X_tend2.

**Comment by MarionBWeinzierl** [comment]
The project is sufficiently underway that it makes sense to close this.
