### ISSUE TITLE
Matching Neural Net input-outputs to SCAM input-outputs

### ISSUE THREAD

**Issue by dorchard** [m2lines/convection-parameterization-in-CAM#2]
We will need to suitably re-interface the Neural Net model, but something we will need to solve is that the co-ordinate schemes between (previously used) SAM and SCAM differ. Therefore some translation with interpolation will be needed.  This will likely need a lot of steer from Judith and Paul.

- Identify input-output interface for the model within SCAM
- Identify the translation and interpolation needed in the co-ordinate schemes
- Design translation scheme
- Write tests to ensure that the translation in-and-out is an isomorphism (no junk no noise).
- Identify CESM/SCAM metrics we can use to test end-to-end after parameterization inserted (continuous integration test)

**Comment by dorchard** [comment]
From @paogorman's M2LInES talk the following 'impedance matching' activities are needed (with some rephrasing from me):

* Match certical coordinate: Interpolate from pressure in CAM to/from reference pressure
profile in anelastic SAM

* Variable conversions: convert tendency of liquid/ice static energy to temperature
   
* Energy conservation: conserve enthalpy in CAM versus static energy in anelastic SAM
(use anelastic-primitive equation analogy). @paogorman does this come for free from some variable conversion, or are we going to need to do something extra?

* Timesteps: subcycling due to mismatch in timesteps

I think it might be best for us to break these into 4 separate issues actually.

**Comment by jatkinson1000** [comment]
The first three may well need to be combined as I suspect they will be interlinked.

The subcycling I agree should be tackled elsewhere, as it is likely non-trivial.

**Comment by paogorman** [comment]
I expect energy conservation will come for free with correct choice of variables

**Comment by dorchard** [comment]
Made a separate issue for subcycling then https://github.com/m2lines/convection-parameterization-in-CAM/issues/37
