### ISSUE TITLE
Subcycling timesteps

### ISSUE THREAD

**Issue by dorchard** [m2lines/convection-parameterization-in-CAM#37]
Due to a mismatch in timesteps between SAM and (S)CAM we will need to do some timestep subcycling.

@paogorman - am I correct in thinking that we will need to run several timesteps of the convection model for every (S)CAM time step then? Or is it the other way round?

**Comment by paogorman** [comment]
Yes, several timesteps of the convection model for every SCAM time step.

**Comment by jatkinson1000** [comment]
Closing this as the subcycling components have been removed from the code in #44 following work in [CAM-ML](https://github.com/m2lines/CAM-ML) where we decided subcycling will be the responsibility of the interface (there we considered using the CLUBB subcycling infrastructure to run YOG but it presented no obvious advantage).
