### ISSUE TITLE
Difference between grid views between SAM and CAM.

### ISSUE THREAD

**Issue by dorchard** [m2lines/convection-parameterization-in-CAM#42]
SAM takes a 3D subgrid, whereas (S)CAM is columnar. We can resolve this by passing 'thin'-3D grids into SAM. But we need to double check with the CAM code.

**Comment by jatkinson1000** [comment]
Ask Judith about this at next development meeting.

**Comment by jatkinson1000** [comment]
As discussed in #43 We will refactor such that the parameterisation takes in a 3D grid of columns, but the x, y coordinates could be lat, lon, or a generic ncol, 1.

Closing this.
